mapping_index =  {
            "settings": {
                "index": {
                    "number_of_shards": 1,
                    "number_of_replicas": 0,
                    "similarity": {
                        "my_similarity": {"type": "LMDirichlet"}
                    },
                },
                "analysis": {
                    "analyzer": {
                        "custom_analyzer": {
                            "type": "custom",
                            "tokenizer": "whitespace",
                            "char_filter": ["html_strip"],
                            "filter": [
                                "synonym",
                                "classic",
                                "lowercase",
                                "remove_digit_token",
                                "remove_link_token",
                                "remove_puntuaction",
                                "remove_length_less_two",
                                "my_stemmer",
                            ],
                        }
                    },
                    "filter": {
                        "my_stemmer": {"type": "stemmer", "name": "porter2"},
                        "remove_digit_token": {
                            "type": "pattern_replace", 
                            "pattern": "^[0-9]+",
                            "replacement": "",
                        },
                        "remove_link_token": {
                            "type": "pattern_replace",
                            "pattern": "^https?:\/\/.*[\r\n]*",
                            "replacement": "",
                        },
                        "remove_puntuaction": {
                            "type": "pattern_replace", 
                            "pattern": "[^0-9A-Za-z@#]",
                            "replacement": "",
                        },
                        "remove_length_less_two": {"type": "length", "min": 2},
                        "synonym":{
                            "type": "synonym",
                            "synonyms": [
                            "laptop, notebook", 
                            "amazing, incredible, unbelievable, improbable, fabulous, wonderful, fantastic, astonishing, astounding, extraordinary",
                            "anger, enrage, infuriate, arouse, nettle, exasperate, inflame, madden",
                            "angry, mad, furious, enraged, excited, wrathful, indignant, exasperated, aroused, inflamed",
                            "answer,reply, respond, retort, acknowledge",
                            "ask, question, demand, request, expect, inquire, query, interrogate, examine, quiz",
                            "awful, dreadful, terrible, abominable, bad, poor, unpleasant",
                            "bad, evil, immoral, wicked, corrupt, sinful, depraved, rotten",
                            "beautiful, pretty, lovely, handsome, attractive, gorgeous, dazzling, splendid, magnificent",
                            "begin, start, open, launch, initiate, commence, inaugurate, originate",
                            "big, enormous, huge, immense, gigantic, vast, colossal, gargantuan, large, sizable, grand",
                            "brave, courageous, fearless, dauntless, intrepid",
                            "break, fracture, rupture, shatter, smash, wreck, crash, demolish, atomize",
                            "come, approach, advance, near, arrive, reach",
                            "cool, chilly, cold, frosty, wintry, icy, frigid",
                            "crooked, bent, twisted, curved, hooked, zigzag",
                            "cry, shout, yell, yowl, scream, roar, bellow, weep, wail, sob, bawl",
                            "cut, gash, slash, prick, nick, sever, slice, carve, cleave, slit, chop, crop, lop, reduce",
                            "dangerous, perilous, hazardous, risky, uncertain, unsafe",
                            "dark, shadowy, unlit, murky, gloomy, dim, dusky, shaded, sunless, black, dismal, sad",
                            "decide, determine, settle, choose, resolve",
                            "definite, certain, sure, positive, determined, clear, distinct, obvious",
                            "delicious, savory, delectable, appetizing, luscious",
                            "describe, portray, characterize, picture, narrate, relate, recount, represent, report, record",
                            "destroy, ruin, demolish, raze, waste, kill, slay, end, extinguish",
                            "difference, disagreement, inequity, contrast, dissimilarity, incompatibility",
                            "do, execute, enact, finish, conclude, effect, accomplish, achieve, attain",
                            "dull, boring, tiring, tiresome, uninteresting, slow, dumb, stupid, unimaginative",
                            "eager,keen, fervent, enthusiastic, involved, interested",
                            "end, stop, finish, terminate, conclude, close, halt, cessation, discontinuance",
                            "fair,just, impartial, unbiased, objective, unprejudiced, honest",
                            "false, fake, fraudulent, counterfeit, spurious, untrue, unfounded, erroneous",
                            "famous, renowned, celebrated, famed, eminent, illustrious, distinguished, noted, notorious",
                            "fast, quick, rapid, speedy, fleet, hasty, snappy, mercurial, swiftly, rapidly, quickly",
                            "fat,stout, corpulent, fleshy, beefy, paunchy, plump, full, rotund, tubby, pudgy, chubby, chunky, burly, bulky, elephantine",
                            "fear, fright, dread, terror, alarm, dismay, anxiety, scare, awe, horror, panic, apprehension",
                            "fly, soar, hover, flit, wing, flee, waft, glide, coast, skim, sail, cruise",
                            "funny, humorous, amusing, droll, comic, comical, laughable, silly",
                            "go, recede, depart, fade, disappear, move, travel, proceed",
                            "good, excellent, fine, superior, wonderful, marvelous, qualified, suited",
                            "great, noteworthy, worthy, distinguished, remarkable, grand, considerable, powerful, much, mighty",
                            "happy, pleased, contented, satisfied, delighted, elated, joyful, cheerful, ecstatic",
                            "hate, despise, loathe, detest, abhor, disfavor, dislike, disapprove, abominate",
                            "have, hold, possess, own, contain, acquire, gain, maintain, believe, bear, beget, occupy, absorb, fill, enjoy",
                            "help, aid, assist, support, encourage, back, attend, serve, relieve, succor, benefit, befriend, abet",
                            "hurry, rush, run, speed, race, hasten, urge, accelerate, bustle",
                            "hurt, damage, harm, injure, wound, distress, afflict, pain",
                            "idea,thought, concept, conception, notion, understanding, opinion, plan, view, belief",
                            "keep, hold, retain, withhold, preserve, maintain, sustain, support",
                            "kill, slay, execute, assassinate, murder, destroy, cancel, abolish",
                            "lazy,indolent, slothful, idle, inactive, sluggish",
                            "make, create, originate, invent, beget, form, construct, design, fabricate, manufacture, produce, build, develop, do",
                            "mark, label, tag, price, ticket, impress, effect, trace, imprint, stamp, brand, sign, note, heed, notice, designate",
                            "mischievous, prankish, playful, naughty, roguish, waggish, impish",        
                            "new, fresh, unique, original, unusual, novel, modern, current, recent",
                            "part,portion, share, piece, allotment, section, fraction, fragment",
                            "place, space, area, spot, plot, region, location",
                            "plan, plot, scheme, design, draw, map, diagram, procedure",
                            "popular, approved, accepted, favorite, celebrated, common, current",
                            "predicament, quandary, dilemma, pickle, problem, plight, spot, scrape, jam",
                            "put, place, set, attach, establish, assign, keep, save, set aside, effect, achieve, do, build",
                            "quiet, silent, still, soundless, mute, tranquil, peaceful, calm, restful",
                            "right, correct, accurate, factual, true, good, just, honest, upright, lawful, moral, proper, suitable, apt, legal, fair",
                            "run, race, speed, hurry, hasten, sprint, dash, rush, escape, elope, flee",
                            "scared, afraid, frightened, alarmed, terrified, panicked, fearful, unnerved, insecure, timid, shy",
                            "show, display, exhibit, present, note, indicate, explain, reveal, prove, demonstrate, expose",
                            "slow,  unhurried, gradual, leisurely, late, behind, tedious, slack",
                            "stop, cease, halt, stay, pause, discontinue, conclude, end, finish, quit",
                            "strange, odd, peculiar, unusual, unfamiliar, uncommon, queer, weird, outlandish, curious, unique, exclusive, irregular",
                            "take, hold, catch, seize, grasp, win, capture, acquire, pick, choose, select, prefer, remove, steal, lift",
                            "tell, disclose, reveal, show, expose, uncover, relate, narrate, inform, advise, explain, divulge, declare",
                            "think, judge, deem, assume, believe, consider, contemplate, reflect, mediate",
                            "trouble, distress, anguish, anxiety, worry, wretchedness, pain, danger, peril",
                            "ugly, hideous, frightful, frightening, shocking, horrible, unpleasant, monstrous",
                            "use, employ, utilize, exhaust, spend, expend, consume, exercise",
                            "wrong, incorrect, inaccurate, mistaken, erroneous, improper, unsuitable"
                                    ]
                        }
                            
                        
                    },
                },
            },
            "mappings": {
                "properties": {
                    "created_at": {"type": "date"},
                    "text": {
                        "type": "text",
                        "analyzer": "custom_analyzer",
                        "similarity": "my_similarity",
                    },
                    "user_name": {"type": "text", "index": True},
                    "like": {"type": "integer", "index": False},
                    "retweet": {"type": "integer", "index": False},
                    "profile_image_url": {"type": "keyword", "index": False},
                    "tweet_url": {"type": "keyword", "index": False},
                    "topic": {"type": "keyword", "index": True},
                    "hashtags":{"type": "keyword", "index": True}
                }
            },
        }